# Numpy

**Numpy** is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension.

### Array Initialization
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [36]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [37]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values from Uniform(0,1)
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.17330409 0.66266507]
 [0.50235096 0.3446549 ]]


You can read about other methods of array creation in the [documentation](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation).

### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [38]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
2
77


We can use `copy` function to avoid modifying the original array:

In [39]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# take a slice AND copy it
b = a[:2, 1:3].copy()

# now b is its own array
print("Before:", a[0,1], b[0,0])   # Before: 2 2

b[0, 0] = 77
print("After modifying b:")
print("a[0,1] =", a[0,1])           # still 2
print("b[0,0] =", b[0,0])           # now 77

Before: 2 2
After modifying b:
a[0,1] = 2
b[0,0] = 77


You can also **mix** integer indexing with slice indexing. However, doing so will yield an array of *lower rank* than the original array. 

In [40]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:



In [41]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [42]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [43]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [44]:
import numpy as np

# Example 2: Thresholding temperature sensor readings
# Imagine you have a week’s worth of hourly temperature measurements (in °C):
temps = np.array([12.1, -2.5,  3.3,  8.8, -0.7,  0.0, 14.2, 15.5])

# Find all readings below freezing (< 0 °C):
below_freeze = temps < 0
# below_freeze → array([False,  True, False, False,  True, False, False, False])

# Extract just those sub‑zero readings:
freezing_temps = temps[below_freeze]
print("Freezing Temps:", freezing_temps)
# Freezing Temps: [-2.5 -0.7]

# You can even modify the original array in‑place:
# e.g. clamp anything below 0 °C up to 0 °C:
temps[temps < 0] = 0
print("Clamped Temps:", temps)
# Clamped Temps: [12.1  0.   3.3  8.8  0.   0.  14.2 15.5]

Freezing Temps: [-2.5 -0.7]
Clamped Temps: [12.1  0.   3.3  8.8  0.   0.  14.2 15.5]


### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [45]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x)
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x)
print(x.dtype)             # Prints "float64"

x = np.array([1.0, 2.0], dtype=np.int64)   # Force a particular datatype
print(x)
print(x.dtype)                         # Prints "int64"


[1 2]
int64
[1. 2.]
float64
[1 2]
int64


You can read all about numpy datatypes in the [documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [46]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [47]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4],[5,6]])

v = np.array([1,2])
w = np.array([3,4])

# Inner product of vectors; both produce 11
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [5 11 17]
print(y.dot(v))
print(np.dot(y, v))

# Matrix / matrix product; both produce the rank 2 array
# [[22 28]
#  [49 64]]
print(x.dot(y))
print(np.dot(x, y))

11
11
[ 5 11 17]
[ 5 11 17]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [48]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](https://numpy.org/doc/stable/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [49]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


Here are more examples on `reshape`:

In [50]:
import numpy as np

# 1D → 2D
a = np.arange(12)           # [0,1,2,…,11], shape (12,)
b = a.reshape((3, 4))       # now shape is (3,4)
c = a.reshape((3, 4), order = 'C') # (row‑major, C‑style)
d = a.reshape((3, 4), order = 'F') # (column‑major, Fortran‑style)

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)

# 2D → 3D
f = b.reshape((2, 2, 3))    # shape (2,2,3)
print("f = ", f)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
b =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
d =  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
f =  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


We can also use `-1` to infer a dimension:

In [51]:
import numpy as np

a = np.arange(24)

# Let NumPy figure out the number of rows
b = a.reshape((-1, 6))    
# here b.shape == (4,6) because 4×6 = 24
print(b.shape)

# Or let it infer columns
c = a.reshape((2, -1, 4))  
# c.shape == (2,3,4)
print(c.shape)

(4, 6)
(2, 3, 4)


Numpy provides many more functions for manipulating arrays; you can see the full list in the [documentation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html).

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [52]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

z = x + v  # Add v to each row of x using broadcasting
print(z)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `z = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)`. Due to broadcasting, this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

To perform column-wise broadcast:

In [53]:
import numpy as np 

x = np.array([[1, 2, 3], [4, 5, 6]]) 
v = np.array([1, 0])

# Reshape v into a column vector w with shape (2, 1)
# so it can broadcast down the rows of x
w = v.reshape(-1, 1)
print("w (column vector):\n", w)
# → [[1]
#    [0]]

# Add w to x: w is broadcast across each row of x
# Effectively adds 1 to the first row and 0 to the second row
y = x + w
print("y = x + w:\n", y)
# → [[2 3 4]
#    [4 5 6]]

# Alternate approach: add v to each column of x
# 1) Transpose x to shape (3,2)
# 2) Add v as a row vector across each row of x.T
# 3) Transpose the result back to (2,3)
z = (x.T + v).T
print("z = (x.T + v).T:\n", z)
# → [[ 2  3  4]   
#    [ 4  5  6]]

w (column vector):
 [[1]
 [0]]
y = x + w:
 [[2 3 4]
 [4 5 6]]
z = (x.T + v).T:
 [[2 3 4]
 [4 5 6]]
